In [159]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [160]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [161]:
X.shape

(150, 4)

In [162]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [163]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 归一化输入数据到0到1之间，防止梯度爆炸

In [164]:
X = X / 8 * 0.99 + 0.01

In [165]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [166]:
X_train.shape

(112, 4)

In [167]:
X_test.shape

(38, 4)

In [168]:
y_train.shape

(112,)

## 暂不使用偏置

In [169]:
oneHot = np.identity(3)
for i in range(oneHot.shape[0]):
    for j in range(oneHot.shape[1]):
        if (oneHot[i,j] == 1):
            oneHot[i,j] = 0.99
        else:
            oneHot[i,j] = 0.01
#数组嵌套操作，慢慢理解
y_true = oneHot[y_train]

In [170]:
oneHot
y_true[:5]

array([[0.01, 0.01, 0.99],
       [0.01, 0.01, 0.99],
       [0.01, 0.99, 0.01],
       [0.01, 0.01, 0.99],
       [0.99, 0.01, 0.01]])

In [171]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

#计算正确率
def ac(y_true, y_predict):
    return sum(y_true == y_predict) / len(y_true)

In [172]:
W1 = np.random.normal(0.0,1,(4,8))
W2 = np.random.normal(0.0,1,(8,3))

eta = 0.01
for i in range(600):
    out1 = np.dot(X_train, W1)
    act1 = sigmoid(out1)
    out2 = np.dot(act1,W2)
    act2 = sigmoid(out2)
    
    #反向传播比较难理解，多角度，简单化
    error = y_true - act2
    hErr = np.dot(error, W2.T)
    
    W2_ = np.dot(act1.T, -error * act2 * (1-act2))
    W1_ = np.dot(X_train.T, -hErr * act1 * (1-act1))
    
    W2 -= W2_ * eta
    W1 -= W1_ * eta
    
o1 = np.dot(X_test, W1)
a1 = sigmoid(o1)
o2 = np.dot(a1,W2)
a2 = sigmoid(o2)

rs = []
for i in range(a2.shape[0]):
    rs.append(np.argmax(a2[i]))
rs = np.array(rs)

ac(y_test, rs)

0.9473684210526315

In [173]:
a2

array([[3.62184387e-02, 4.42054421e-01, 5.35602845e-01],
       [1.77836030e-02, 4.25585603e-01, 7.49283356e-01],
       [2.42081358e-02, 4.40972352e-01, 6.77551179e-01],
       [9.03290545e-01, 2.12635574e-01, 1.24080852e-03],
       [9.27718874e-01, 1.97678606e-01, 1.10393514e-03],
       [1.78930395e-01, 4.23797273e-01, 1.27370451e-01],
       [9.38197597e-01, 1.88170399e-01, 7.36295299e-04],
       [1.70988421e-01, 4.29394775e-01, 1.34779320e-01],
       [9.18115554e-01, 2.22034170e-01, 1.29035056e-03],
       [3.85844120e-02, 4.40210236e-01, 5.14614719e-01],
       [1.27006086e-02, 4.38233725e-01, 8.34217522e-01],
       [3.55275568e-02, 4.53975211e-01, 5.49225494e-01],
       [9.42585353e-01, 1.85177490e-01, 6.74921618e-04],
       [8.89381986e-01, 2.37075604e-01, 1.74949253e-03],
       [9.46863453e-01, 1.68494873e-01, 5.69484518e-04],
       [1.59112670e-02, 4.43269913e-01, 7.76793580e-01],
       [4.27445498e-02, 4.37458403e-01, 4.75759680e-01],
       [9.33682007e-01, 1.97194

### >参考视频https://www.bilibili.com/video/BV1qE411b7gU?from=search&seid=900318112246919302