In [1]:
import numpy as np
import pandas as pd

### 运行pagerank

In [3]:
!python pagerank.py

[[0.37918179]
 [0.40298726]
 [0.21783095]]


### 草稿

In [52]:
pd.read_csv('page_test.csv')

A  B  C
0  0  0  0
1  1  0  1
2  1  0  0

In [50]:
data = {'A':[0,1,1],'B':[0,0,0],'C':[0,1,0]}
df = pd.DataFrame(data)

In [51]:
df.to_csv('page_test.csv',index=None)

In [14]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [19]:
df.columns

Index(['1', '2', '3'], dtype='object')

In [21]:
df['1'].values

array([2, 3, 0], dtype=int64)

In [25]:
for each in df.loc[0]:
    a = each
print(a)

1


In [53]:
df.iloc[:,0]

0    0
1    1
2    1
Name: A, dtype: int64

In [56]:
a = np.ones((5,1)) / 5

In [60]:
a

array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]])

In [61]:
sum(a)

array([1.])

In [62]:
np.sum(a)

1.0

In [63]:
a= np.mat([1,1,0])

In [64]:
a

matrix([[1, 1, 0]])

In [66]:
a/np.sum(a)

matrix([[0.5, 0.5, 0. ]])

In [82]:
a = np.mat([[1,2,4],[3,4,7]])

In [73]:
a

matrix([[1, 2, 4],
        [3, 4, 7]])

In [79]:
a[:,1] = a[:,1]/np.sum(a[:,1])

In [80]:
a

matrix([[1, 0, 4],
        [3, 0, 7]])

In [83]:
a[:,1]/np.sum(a[:,1])

matrix([[0.33333333],
        [0.66666667]])